apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo
  namespace: jenkins-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: standard-rwo

